baseURL = '/'
languageCode = 'en-us'
title = 'Harry! Learn!'
theme = "hugo-PaperMod"

[outputs]
home = [ "HTML", "RSS", "JSON" ]


[menu]
[[menu.main]]
  identifier = 'Archive'
  name = 'Archive'
  pre = "<i class='fa fa-heart'></i>"
  url = '/archive/'
  weight = -110


[[menu.main]]
  identifier = 'Search'
  name = 'Search'
  pre = "<i class='fa fa-heart'></i>"
  url = '/Search/'
  weight = -100

[params.homeInfoParams]
Title = "人生波澜壮阔 / Life is vast and magnificent."

[params]   
gtm = "GTM-WXVJN82"
