baseURL = '/'
languageCode = 'en-us'
title = 'H. NI'
theme = "hugo-PaperMod"

[outputs]
home = [ "HTML", "RSS", "JSON" ]


[menu]
[[menu.main]]
  identifier = 'Archive'
  name = 'Archive'
  pre = "<i class='fa fa-heart'></i>"
  url = '/archive/'
  weight = -110


[[menu.main]]
  identifier = 'Search'
  name = 'Search'
  pre = "<i class='fa fa-heart'></i>"
  url = '/Search/'
  weight = -100

[params.homeInfoParams]
Title = "Haojie Ni's Blog"
Content = """你好 / Welcome / Willkommen 👋

This is my little corner on the internet where I share learning notes and some nerdy thoughts—hopefully you’ll find something useful (or at least fun) here.  

Right now, I’m exploring opportunities as a software engineer in Germany, especially around Python Backend, DevOps, and Data Engineering. I spend most of my time in Python and Linux, and I enjoy tinkering with them a lot.  

Feel free to check out my [LinkedIn](https://www.linkedin.com/in/haojie-ni/) or [GitHub](https://github.com/Aken-2019) if you’re curious about what I’ve been working on.  
And if you’d like the full story, my CV is available as a [PDF](/cv/H_NI-Python-Backend.pdf).


"""

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/Aken-2019"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/haojie-ni/"

[params]   
gtm = "GTM-WXVJN82"
